"""practicals gamification ads announcements

Revision ID: 1240b46aa684
Revises: de453e237e0d
Create Date: 2026-09-07 01:22:46.238330
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1240b46aa684'
down_revision = 'de453e237e0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_key', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('target_url', sa.String(length=500), nullable=True),
    sa.Column('placement', sa.String(length=50), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('alt_text', sa.String(length=300), nullable=True),
    sa.Column('advertiser', sa.String(length=200), nullable=True),
    sa.Column('campaign_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('publish_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expire_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gamification_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('metadata_json', sa.UnicodeText(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gamification_events_user_id'), 'gamification_events', ['user_id'], unique=False)
    op.create_table('practical_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('practical_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('step_text', sa.Text(), nullable=False),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['practical_id'], ['practicals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_key', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('earned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_badges_badge_key'), 'user_badges', ['badge_key'], unique=False)
    op.create_index(op.f('ix_user_badges_user_id'), 'user_badges', ['user_id'], unique=False)
    op.create_table('user_streaks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_active_on', sa.Date(), nullable=True),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('xp_this_month', sa.Integer(), nullable=False),
    sa.Column('total_attempts', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_streaks_user_id'), 'user_streaks', ['user_id'], unique=False)
    op.create_table('xp_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xp_transactions_user_id'), 'xp_transactions', ['user_id'], unique=False)
    op.add_column('practicals', sa.Column('topic_slug', sa.String(length=150), nullable=True))
    op.add_column('practicals', sa.Column('requirements', sa.Text(), nullable=True))
    op.add_column('practicals', sa.Column('principle', sa.Text(), nullable=True))
    op.add_column('practicals', sa.Column('preparation', sa.Text(), nullable=True))
    op.add_column('practicals', sa.Column('observation', sa.Text(), nullable=True))
    op.add_column('practicals', sa.Column('interpretation', sa.Text(), nullable=True))
    op.add_column('practicals', sa.Column('common_mistakes', sa.Text(), nullable=True))
    op.add_column('practicals', sa.Column('safety_notes', sa.Text(), nullable=True))
    op.add_column('practicals', sa.Column('clinical_significance', sa.Text(), nullable=True))
    op.add_column('practicals', sa.Column('reference_text', sa.Text(), nullable=True))
    op.create_index(op.f('ix_practicals_topic_slug'), 'practicals', ['topic_slug'], unique=False)
    op.drop_column('practicals', 'procedure')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practicals', sa.Column('procedure', sa.TEXT(), nullable=True))
    op.drop_index(op.f('ix_practicals_topic_slug'), table_name='practicals')
    op.drop_column('practicals', 'reference_text')
    op.drop_column('practicals', 'clinical_significance')
    op.drop_column('practicals', 'safety_notes')
    op.drop_column('practicals', 'common_mistakes')
    op.drop_column('practicals', 'interpretation')
    op.drop_column('practicals', 'observation')
    op.drop_column('practicals', 'preparation')
    op.drop_column('practicals', 'principle')
    op.drop_column('practicals', 'requirements')
    op.drop_column('practicals', 'topic_slug')
    op.drop_index(op.f('ix_xp_transactions_user_id'), table_name='xp_transactions')
    op.drop_table('xp_transactions')
    op.drop_index(op.f('ix_user_streaks_user_id'), table_name='user_streaks')
    op.drop_table('user_streaks')
    op.drop_index(op.f('ix_user_badges_user_id'), table_name='user_badges')
    op.drop_index(op.f('ix_user_badges_badge_key'), table_name='user_badges')
    op.drop_table('user_badges')
    op.drop_table('practical_steps')
    op.drop_index(op.f('ix_gamification_events_user_id'), table_name='gamification_events')
    op.drop_table('gamification_events')
    op.drop_table('announcements')
    op.drop_table('ads')
    # ### end Alembic commands ###
