"""analytics security partnerships

Revision ID: 61378de8dd44
Revises: 1240b46aa684
Create Date: 2026-09-07 04:35:43.096350
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61378de8dd44'
down_revision = '1240b46aa684'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=150), nullable=True),
    sa.Column('website', sa.String(length=400), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_key', sa.String(length=300), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutions_name'), 'institutions', ['name'], unique=False)
    op.create_table('partnership_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_type', sa.String(length=60), nullable=False),
    sa.Column('organization_name', sa.String(length=300), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=60), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('goal', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('handled_by', sa.String(length=255), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partnership_requests_contact_email'), 'partnership_requests', ['contact_email'], unique=False)
    op.create_table('analytics_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=True),
    sa.Column('session_id', sa.String(length=80), nullable=True),
    sa.Column('path', sa.String(length=300), nullable=True),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_events_event_type'), 'analytics_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_analytics_events_session_id'), 'analytics_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_analytics_events_user_id'), 'analytics_events', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=60), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_table('search_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('query', sa.String(length=300), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('is_failed', sa.Boolean(), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_events_query'), 'search_events', ['query'], unique=False)
    op.create_index(op.f('ix_search_events_user_id'), 'search_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_events_user_id'), table_name='search_events')
    op.drop_index(op.f('ix_search_events_query'), table_name='search_events')
    op.drop_table('search_events')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_analytics_events_user_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_session_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_event_type'), table_name='analytics_events')
    op.drop_table('analytics_events')
    op.drop_index(op.f('ix_partnership_requests_contact_email'), table_name='partnership_requests')
    op.drop_table('partnership_requests')
    op.drop_index(op.f('ix_institutions_name'), table_name='institutions')
    op.drop_table('institutions')
    # ### end Alembic commands ###
