"""initial_schema

Revision ID: 6e86f8b978f5
Revises: 
Create Date: 2026-09-07 00:30:56.888569
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e86f8b978f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anatomical_regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['anatomical_regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anatomical_regions_slug'), 'anatomical_regions', ['slug'], unique=True)
    op.create_table('anatomical_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anatomical_systems_slug'), 'anatomical_systems', ['slug'], unique=True)
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('affiliation', sa.String(length=300), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authors_name'), 'authors', ['name'], unique=False)
    op.create_table('flashcards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_slug', sa.String(length=100), nullable=False),
    sa.Column('topic_slug', sa.String(length=150), nullable=True),
    sa.Column('front', sa.Text(), nullable=False),
    sa.Column('back', sa.Text(), nullable=False),
    sa.Column('card_type', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcards_subject_slug'), 'flashcards', ['subject_slug'], unique=False)
    op.create_index(op.f('ix_flashcards_topic_slug'), 'flashcards', ['topic_slug'], unique=False)
    op.create_table('licenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('license_url', sa.String(length=500), nullable=True),
    sa.Column('commercial_allowed', sa.Boolean(), nullable=False),
    sa.Column('modification_allowed', sa.Boolean(), nullable=False),
    sa.Column('redistribution_allowed', sa.Boolean(), nullable=False),
    sa.Column('attribution_required', sa.Boolean(), nullable=False),
    sa.Column('sharealike_required', sa.Boolean(), nullable=False),
    sa.Column('ai_ingestion_allowed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('practicals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('procedure', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practicals_subject_slug'), 'practicals', ['subject_slug'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_slug', sa.String(length=100), nullable=False),
    sa.Column('topic_slug', sa.String(length=150), nullable=True),
    sa.Column('stem', sa.Text(), nullable=False),
    sa.Column('qtype', sa.String(length=30), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('reference', sa.String(length=300), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('learning_objective', sa.Text(), nullable=True),
    sa.Column('reviewer', sa.String(length=150), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_subject_slug'), 'questions', ['subject_slug'], unique=False)
    op.create_index(op.f('ix_questions_topic_slug'), 'questions', ['topic_slug'], unique=False)
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_slug'), 'subjects', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supabase_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_supabase_id'), 'users', ['supabase_id'], unique=True)
    op.create_table('viva_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_slug', sa.String(length=100), nullable=False),
    sa.Column('topic_slug', sa.String(length=150), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('model_answer', sa.Text(), nullable=False),
    sa.Column('key_points', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_viva_questions_subject_slug'), 'viva_questions', ['subject_slug'], unique=False)
    op.create_index(op.f('ix_viva_questions_topic_slug'), 'viva_questions', ['topic_slug'], unique=False)
    op.create_table('anatomical_structures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stable_structure_id', sa.String(length=120), nullable=True),
    sa.Column('preferred_name', sa.String(length=200), nullable=False),
    sa.Column('latin_name', sa.String(length=200), nullable=True),
    sa.Column('synonyms', sa.Text(), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('clinical_notes', sa.Text(), nullable=True),
    sa.Column('surface_anatomy', sa.Text(), nullable=True),
    sa.Column('embryology', sa.Text(), nullable=True),
    sa.Column('histology', sa.Text(), nullable=True),
    sa.Column('radiology', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['anatomical_structures.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['anatomical_regions.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['anatomical_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anatomical_structures_preferred_name'), 'anatomical_structures', ['preferred_name'], unique=False)
    op.create_index(op.f('ix_anatomical_structures_stable_structure_id'), 'anatomical_structures', ['stable_structure_id'], unique=True)
    op.create_table('atlas_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('source', sa.String(length=300), nullable=True),
    sa.Column('license', sa.String(length=100), nullable=True),
    sa.Column('creator', sa.String(length=200), nullable=True),
    sa.Column('file_key', sa.String(length=500), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('optimization_status', sa.String(length=40), nullable=False),
    sa.Column('review_status', sa.String(length=40), nullable=False),
    sa.Column('default_visibility', sa.JSON(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['anatomical_regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flashcard_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('quality', sa.Integer(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['flashcards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flashcard_reviews_user_id'), 'flashcard_reviews', ['user_id'], unique=False)
    op.create_table('question_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_option_id', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_attempts_user_id'), 'question_attempts', ['user_id'], unique=False)
    op.create_table('question_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('resource_type', sa.String(length=60), nullable=False),
    sa.Column('creator', sa.String(length=200), nullable=True),
    sa.Column('publisher', sa.String(length=200), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('local_storage_key', sa.String(length=500), nullable=True),
    sa.Column('license_id', sa.Integer(), nullable=True),
    sa.Column('rights_status', sa.String(length=40), nullable=False),
    sa.Column('ai_usage_status', sa.String(length=20), nullable=False),
    sa.Column('attribution_text', sa.Text(), nullable=True),
    sa.Column('review_status', sa.String(length=40), nullable=False),
    sa.Column('medical_review_status', sa.String(length=40), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('verified_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_resource_type'), 'resources', ['resource_type'], unique=False)
    op.create_index(op.f('ix_resources_title'), 'resources', ['title'], unique=False)
    op.create_table('study_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('subject_slug', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_sessions_user_id'), 'study_sessions', ['user_id'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('learning_objectives', sa.Text(), nullable=True),
    sa.Column('content_markdown', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'slug', name='uq_subject_topic_slug')
    )
    op.create_index(op.f('ix_topics_slug'), 'topics', ['slug'], unique=False)
    op.create_table('user_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_slug', sa.String(length=100), nullable=False),
    sa.Column('topic_slug', sa.String(length=150), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('mastery', sa.Float(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_progress_subject_slug'), 'user_progress', ['subject_slug'], unique=False)
    op.create_index(op.f('ix_user_progress_topic_slug'), 'user_progress', ['topic_slug'], unique=False)
    op.create_index(op.f('ix_user_progress_user_id'), 'user_progress', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role', name='uq_user_role')
    )
    op.create_table('viva_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('viva_question_id', sa.Integer(), nullable=False),
    sa.Column('student_answer', sa.Text(), nullable=True),
    sa.Column('self_rating', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['viva_question_id'], ['viva_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_viva_attempts_user_id'), 'viva_attempts', ['user_id'], unique=False)
    op.create_table('anatomical_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('structure_a', sa.Integer(), nullable=False),
    sa.Column('structure_b', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['structure_a'], ['anatomical_structures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['structure_b'], ['anatomical_structures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atlas_annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('structure_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('position_z', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['atlas_models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['structure_id'], ['anatomical_structures.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atlas_model_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('structure_id', sa.Integer(), nullable=True),
    sa.Column('mesh_name', sa.String(length=200), nullable=False),
    sa.Column('material', sa.String(length=200), nullable=True),
    sa.Column('visibility', sa.Boolean(), nullable=False),
    sa.Column('highlight_config', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['atlas_models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['structure_id'], ['anatomical_structures.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atlas_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('reviewer', sa.String(length=150), nullable=False),
    sa.Column('review_type', sa.String(length=40), nullable=False),
    sa.Column('result', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['atlas_models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('edition', sa.String(length=100), nullable=True),
    sa.Column('publisher', sa.String(length=200), nullable=True),
    sa.Column('isbn', sa.String(length=50), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('subject_slug', sa.String(length=100), nullable=True),
    sa.Column('reading_progress', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', name='uq_book_resource')
    )
    op.create_table('resource_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('version_label', sa.String(length=50), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('chapter_index', sa.Integer(), nullable=False),
    sa.Column('topic_slug', sa.String(length=150), nullable=True),
    sa.Column('content_key', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_chapters_topic_slug'), 'book_chapters', ['topic_slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_chapters_topic_slug'), table_name='book_chapters')
    op.drop_table('book_chapters')
    op.drop_table('resource_versions')
    op.drop_table('books')
    op.drop_table('atlas_reviews')
    op.drop_table('atlas_model_parts')
    op.drop_table('atlas_annotations')
    op.drop_table('anatomical_relationships')
    op.drop_index(op.f('ix_viva_attempts_user_id'), table_name='viva_attempts')
    op.drop_table('viva_attempts')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_user_progress_user_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_topic_slug'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_subject_slug'), table_name='user_progress')
    op.drop_table('user_progress')
    op.drop_index(op.f('ix_topics_slug'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_study_sessions_user_id'), table_name='study_sessions')
    op.drop_table('study_sessions')
    op.drop_index(op.f('ix_resources_title'), table_name='resources')
    op.drop_index(op.f('ix_resources_resource_type'), table_name='resources')
    op.drop_table('resources')
    op.drop_table('question_options')
    op.drop_index(op.f('ix_question_attempts_user_id'), table_name='question_attempts')
    op.drop_table('question_attempts')
    op.drop_index(op.f('ix_flashcard_reviews_user_id'), table_name='flashcard_reviews')
    op.drop_table('flashcard_reviews')
    op.drop_table('atlas_models')
    op.drop_index(op.f('ix_anatomical_structures_stable_structure_id'), table_name='anatomical_structures')
    op.drop_index(op.f('ix_anatomical_structures_preferred_name'), table_name='anatomical_structures')
    op.drop_table('anatomical_structures')
    op.drop_index(op.f('ix_viva_questions_topic_slug'), table_name='viva_questions')
    op.drop_index(op.f('ix_viva_questions_subject_slug'), table_name='viva_questions')
    op.drop_table('viva_questions')
    op.drop_index(op.f('ix_users_supabase_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subjects_slug'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_questions_topic_slug'), table_name='questions')
    op.drop_index(op.f('ix_questions_subject_slug'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_practicals_subject_slug'), table_name='practicals')
    op.drop_table('practicals')
    op.drop_table('licenses')
    op.drop_index(op.f('ix_flashcards_topic_slug'), table_name='flashcards')
    op.drop_index(op.f('ix_flashcards_subject_slug'), table_name='flashcards')
    op.drop_table('flashcards')
    op.drop_index(op.f('ix_authors_name'), table_name='authors')
    op.drop_table('authors')
    op.drop_index(op.f('ix_anatomical_systems_slug'), table_name='anatomical_systems')
    op.drop_table('anatomical_systems')
    op.drop_index(op.f('ix_anatomical_regions_slug'), table_name='anatomical_regions')
    op.drop_table('anatomical_regions')
    # ### end Alembic commands ###
