"""reports embeddings profile

Revision ID: 744117468f95
Revises: 61378de8dd44
Create Date: 2026-09-07 05:01:52.861885
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '744117468f95'
down_revision = '61378de8dd44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_key', sa.String(length=300), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('href', sa.String(length=400), nullable=True),
    sa.Column('vector_json', sa.Text(), nullable=True),
    sa.Column('model_tag', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_embeddings_source_id'), 'content_embeddings', ['source_id'], unique=False)
    op.create_index(op.f('ix_content_embeddings_source_key'), 'content_embeddings', ['source_key'], unique=False)
    op.create_index(op.f('ix_content_embeddings_source_type'), 'content_embeddings', ['source_type'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('target_slug', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('handled_by', sa.String(length=200), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_category'), 'reports', ['category'], unique=False)
    op.create_index(op.f('ix_reports_reporter_id'), 'reports', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_reports_target_type'), 'reports', ['target_type'], unique=False)
    op.add_column('users', sa.Column('course', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('year_of_study', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('university', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('preferred_language', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('study_goal', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'study_goal')
    op.drop_column('users', 'preferred_language')
    op.drop_column('users', 'country')
    op.drop_column('users', 'university')
    op.drop_column('users', 'year_of_study')
    op.drop_column('users', 'course')
    op.drop_index(op.f('ix_reports_target_type'), table_name='reports')
    op.drop_index(op.f('ix_reports_reporter_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_category'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_content_embeddings_source_type'), table_name='content_embeddings')
    op.drop_index(op.f('ix_content_embeddings_source_key'), table_name='content_embeddings')
    op.drop_index(op.f('ix_content_embeddings_source_id'), table_name='content_embeddings')
    op.drop_table('content_embeddings')
    # ### end Alembic commands ###
