"""topic knowledge graph prerequisites

Revision ID: d021308bae4f
Revises: 744117468f95
Create Date: 2026-09-07 05:30:51.919733
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd021308bae4f'
down_revision = '744117468f95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_topic_id', sa.Integer(), nullable=False),
    sa.Column('to_topic_id', sa.Integer(), nullable=False),
    sa.Column('link_type', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_topic_id', 'to_topic_id', 'link_type', name='uq_topic_link')
    )
    op.create_index(op.f('ix_topic_links_from_topic_id'), 'topic_links', ['from_topic_id'], unique=False)
    op.create_index(op.f('ix_topic_links_to_topic_id'), 'topic_links', ['to_topic_id'], unique=False)
    op.add_column('topics', sa.Column('difficulty', sa.String(length=20), server_default='medium', nullable=False))
    op.add_column('topics', sa.Column('est_minutes', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topics', 'est_minutes')
    op.drop_column('topics', 'difficulty')
    op.drop_index(op.f('ix_topic_links_to_topic_id'), table_name='topic_links')
    op.drop_index(op.f('ix_topic_links_from_topic_id'), table_name='topic_links')
    op.drop_table('topic_links')
    # ### end Alembic commands ###
